In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [4]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.8626,  0.3258,  1.0351],
        [-0.6408, -0.2184,  0.4262]], requires_grad=True)
tensor([0.4998, 0.8745], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[129.8033, -42.2088],
        [173.9078, -49.3790],
        [179.2321, -59.4173],
        [140.7889, -58.1089],
        [163.7479, -34.4708]], grad_fn=<AddBackward0>)


In [8]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [10]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(14033.5859, grad_fn=<DivBackward0>)


In [11]:
# Compute gradients
loss.backward()

In [12]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[ 0.8626,  0.3258,  1.0351],
        [-0.6408, -0.2184,  0.4262]], requires_grad=True)
tensor([[  7078.1025,   6426.3052,   4252.1284],
        [-11781.3252, -13071.6289,  -7974.2852]])


In [13]:
w
w.grad

tensor([[  7078.1025,   6426.3052,   4252.1284],
        [-11781.3252, -13071.6289,  -7974.2852]])

In [14]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [15]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(14033.5859, grad_fn=<DivBackward0>)


In [16]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [17]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[118.5014, -21.4201],
        [159.0894, -22.0500],
        [161.9958, -27.0251],
        [129.2318, -37.5192],
        [149.7175,  -8.2096]], grad_fn=<AddBackward0>)


In [18]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(9637.6543, grad_fn=<DivBackward0>)


In [19]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[  5914.1045,   5183.3486,   3483.3677],
        [ -9634.3643, -10762.6709,  -6549.9199]])
tensor([  67.5072, -115.2448])


In [20]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [21]:
print(w)
print(b)

tensor([[ 0.7327,  0.2097,  0.9577],
        [-0.4267,  0.0200,  0.5714]], requires_grad=True)
tensor([0.4983, 0.8771], requires_grad=True)


In [22]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(6673.0303, grad_fn=<DivBackward0>)


In [23]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [24]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(159.3502, grad_fn=<DivBackward0>)


In [25]:
# Predictions
preds

tensor([[ 62.3021,  72.3061],
        [ 87.6222, 102.0088],
        [ 98.1202, 126.7063],
        [ 50.6557,  47.7646],
        [ 94.1798, 115.3674]], grad_fn=<AddBackward0>)

In [26]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [27]:
import torch.nn as nn

In [28]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]],
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]],
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [29]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])

In [30]:
from torch.utils.data import TensorDataset

In [31]:
# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [32]:
from torch.utils.data import DataLoader

In [33]:
# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [34]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 74.,  66.,  43.],
        [102.,  43.,  37.],
        [ 92.,  87.,  64.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.]])
tensor([[ 57.,  69.],
        [ 22.,  37.],
        [ 82., 100.],
        [ 81., 101.],
        [103., 119.]])


In [35]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.1978,  0.1472, -0.4824],
        [ 0.2010, -0.1238, -0.4007]], requires_grad=True)
Parameter containing:
tensor([ 0.5246, -0.5402], requires_grad=True)


In [36]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.1978,  0.1472, -0.4824],
         [ 0.2010, -0.1238, -0.4007]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5246, -0.5402], requires_grad=True)]

In [37]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-24.7940, -11.3911],
        [-35.3927, -18.7875],
        [-24.9346, -22.8832],
        [-31.1703,  -0.1854],
        [-32.7569, -26.6050],
        [-25.1390, -11.0663],
        [-36.0223, -19.0644],
        [-25.6148, -23.0829],
        [-30.8253,  -0.5102],
        [-33.0414, -27.2067],
        [-25.4236, -11.6680],
        [-35.7378, -18.4627],
        [-24.3050, -22.6063],
        [-30.8858,   0.4164],
        [-32.4118, -26.9298]], grad_fn=<AddmmBackward0>)

In [38]:
# Import nn.functional
import torch.nn.functional as F

In [39]:
# Define loss function
loss_fn = F.mse_loss

In [40]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(12984.0225, grad_fn=<MseLossBackward0>)


In [41]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [42]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [43]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 42.9652
Epoch [20/100], Loss: 310.3081
Epoch [30/100], Loss: 326.5407
Epoch [40/100], Loss: 243.2272
Epoch [50/100], Loss: 205.1056
Epoch [60/100], Loss: 108.6269
Epoch [70/100], Loss: 105.5006
Epoch [80/100], Loss: 69.6480
Epoch [90/100], Loss: 53.9255
Epoch [100/100], Loss: 61.1821


In [44]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.4807,  72.1828],
        [ 78.4000,  96.8902],
        [124.9761, 139.1040],
        [ 27.9492,  47.4741],
        [ 91.4129, 106.3116],
        [ 57.2759,  71.2177],
        [ 77.4971,  96.1856],
        [124.8873, 139.3301],
        [ 29.1540,  48.4393],
        [ 91.7149, 106.5721],
        [ 57.5778,  71.4782],
        [ 77.1952,  95.9251],
        [125.8790, 139.8086],
        [ 27.6473,  47.2136],
        [ 92.6177, 107.2767]], grad_fn=<AddmmBackward0>)

In [45]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [46]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[54.1588, 68.6000]], grad_fn=<AddmmBackward0>)